# Generated by Django 5.2.6 on 2025-10-10 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Room name should only contain letters, numbers, and spaces.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
