# Generated by Django 5.2.6 on 2025-10-03 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('SE', 'Science & Engineering'), ('SSE', 'Social Sciences & Education'), ('IT', 'Interdisciplinary Themes')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'Description must be at least 30 characters long.')])),
            ],
        ),
    ]
