# Generated by Django 5.2.6 on 2025-10-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_role', models.CharField(choices=[('chair', 'Chair'), ('co-chair', 'Co-chair'), ('committee', 'Organizing Committee Member')], default='comite', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='ConferenceApp.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('payed', models.BooleanField(default=False)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
