# Generated by Django 5.2.6 on 2025-10-10 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_alter_submission_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='The conference name should only contain letters and spaces.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
