# Generated by Django 5.2.6 on 2025-10-10 13:29

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[UserApp.models.validate_academic_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres, espaces ou tirets.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres, espaces ou tirets.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\s-]+$')]),
        ),
    ]
